version: '3.9'

services:
  # kafka
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.6.2
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    restart: always

  kafka:
    container_name: kafka
    hostname: kafka
    image: wurstmeister/kafka:2.13-2.7.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "bestseller:1:1"
      # topic:partition:replica
      # compact = cleanup.policy set to compact
    depends_on:
      - zookeeper

  # kafka producer
#  kafka_cont:
#    container_name: kafka_controller
#    image: ubuntu:18.04
#    env_file: ./kafka_cont/env
#    volumes:
#      - ./kafka_cont:/home/ubuntu
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - data_platform
#    depends_on:
#      - kafka

#  mysql_8:
#    container_name: mysql_8
#    image: mysql:8.0
#    privileged: true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./db/mysql8:/var/lib/mysql
#    ports:
#      - 3306:3306
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#      - --default-authentication-plugin=mysql_native_password
#      - --skip-grant-tables
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      MYSQL_ROOT_PASSWORD: donghyun
#      MYSQL_DATABASE: waisy
#      MYSQL_USER: waisy
#      MYSQL_PASSWORD: donghyun
#    restart: always

  mysql_5:
    container_name: mysql_5
    image: mysql:5.7
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./db/mysql5:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --skip-grant-tables
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: donghyun
      MYSQL_DATABASE: waisy
      MYSQL_USER: waisy
      MYSQL_PASSWORD: donghyun
    restart: always

